FROM amazonlinux:2023

RUN yum install -y git tar gzip gcc-c++ make python3 curl \
    libX11-devel libxkbfile-devel libsecret-devel krb5-devel \
    && curl -fsSL https://rpm.nodesource.com/setup_22.x | bash - \
    && yum install -y nodejs \
    && curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && yum clean all

ENV PATH="/root/.cargo/bin:${PATH}"
WORKDIR /workspace
